# Generated by Django 3.2.4 on 2022-12-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('population', models.IntegerField()),
                ('metropolitan', models.IntegerField()),
                ('sex_ratio', models.IntegerField()),
                ('literacy', models.FloatField()),
            ],
        ),
    ]
